#!/usr/bin/env bash
set -eu -o pipefail

echo -ne '\033]0;'$0'\007'
nix-shell -A shells.ghcjs --run '
  cabal --project-file=cabal-ghcjs.project --builddir=dist-ghcjs new-build exe:frontend
  mkdir -p frontendJs
  (cd frontendJs; ln -sfT ../dist-ghcjs/build/*/ghcjs-*/frontend-*/c/frontend/build/frontend/frontend.jsexe frontend.jsexe)
  '

# GC flags
# If BUSY_YIELD < SCHED_QUANTUM, only one thread ever seems to get to run.
# -DGHCJS_GC_INTERVAL=60000 -DGHCJS_BUSY_YIELD=5 -DGHCJS_SCHED_QUANTUM=5

# Xtreme optimization
# -O2 -fplugin=Reflex.Optimizer -fexpose-all-unfoldings -fspecialise-aggressively

# dump ghc intermediate outputs for analysis
# -dumpdir=dump-js -ddump-to-file -ddump-simpl -ddump-hi -dppr-cols=200 -ddump-rule-firings -dsuppress-all
