#!/usr/bin/env bash
ghci -I../dep/reflex-dom/reflex-dom-core/dist/build/autogen \
-i../dep/reflex-dom/reflex-dom/src:../dep/reflex-dom/reflex-dom-core/src:../dep/reflex-dom/reflex-dom-core/src-ghc:./.obelisk/impl/lib/executable-config/inject/src:./.obelisk/impl/lib/executable-config/lookup/src:./.obelisk/impl/lib/route/src:./.obelisk/impl/lib/frontend/src:./.obelisk/impl/lib/backend/src:./.obelisk/impl/lib/run/src:./frontend/src:./backend/src:./common/src:. \
-dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir \
dist/build -stubdir dist/build -idist/build -isrc -isrc-ghc \
-idist../dep/reflex-dom/reflex-dom-core/build/autogen \
-idist../dep/reflex-dom/reflex-dom-core/build/global-autogen \
-Idist../dep/reflex-dom/reflex-dom-core/build/autogen \
-Idist../dep/reflex-dom/reflex-dom-core/build/global-autogen \
-Idist../dep/reflex-dom/reflex-dom-core/build -optP-DUSE_TEMPLATE_HASKELL \
-ignore-dot-ghci \
-ghci-script obrun
 "$@"
