name: frontend
version: '0.1'

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base
    - common
    - obelisk-frontend
    - obelisk-route
    - reflex-dom
    - static
    - text

executables:
  frontend:
    main: main.hs
    source-dirs: src-bin
    ghc-options: -threaded
    dependencies:
      - base
      - common
      - frontend
      - obelisk-frontend
      - obelisk-route
      - reflex-dom
      - static
    when:
      - condition: os(osx)
        ghc-options: -dynamic
