cabal-version: 2.2
name: obelisk-executable-config-inject
version: 0.1
build-type: Simple

common common
  default-language: Haskell2010

  default-extensions:
      ApplicativeDo
    , BangPatterns
    , CPP
    , ConstraintKinds
    , DataKinds
    , DefaultSignatures
    , DeriveFunctor
    , DeriveGeneric
    , EmptyCase
    , EmptyDataDecls
    , FlexibleContexts
    , FlexibleInstances
    , FunctionalDependencies
    , GADTs
    , GeneralizedNewtypeDeriving
    , ImportQualifiedPost
    , KindSignatures
    , LambdaCase
    , LiberalTypeSynonyms
    , MultiParamTypeClasses
    , NumDecimals
    , OverloadedStrings
    , PackageImports
    , PatternSynonyms
    , QuantifiedConstraints
    , RankNTypes
    , RecursiveDo
    , ScopedTypeVariables
    , StandaloneDeriving
    , TemplateHaskell
    , TemplateHaskellQuotes
    , TupleSections
    , TypeApplications
    , TypeFamilies
    , TypeOperators
    , UndecidableInstances
    , ViewPatterns

library
  import: common
  hs-source-dirs: src

  build-depends:
    base,
    bytestring,
    base64-bytestring,
    containers,
    reflex-dom-core,
    text

  exposed-modules: Obelisk.ExecutableConfig.Inject
  ghc-options: -Wall -Werror -Wredundant-constraints -Wincomplete-uni-patterns -Wincomplete-record-updates -O
