cabal-version: 2.2
name: obelisk-snap-extras
version: 0.1
synopsis: Extra functionality for Snap that should be considered for upstreaming
license: BSD-3-Clause
build-type: Simple

common common
  default-language: Haskell2010

  default-extensions:
      ApplicativeDo
    , BangPatterns
    , CPP
    , ConstraintKinds
    , DataKinds
    , DefaultSignatures
    , DeriveFunctor
    , DeriveGeneric
    , EmptyCase
    , EmptyDataDecls
    , FlexibleContexts
    , FlexibleInstances
    , FunctionalDependencies
    , GADTs
    , GeneralizedNewtypeDeriving
    , ImportQualifiedPost
    , KindSignatures
    , LambdaCase
    , LiberalTypeSynonyms
    , MultiParamTypeClasses
    , NumDecimals
    , OverloadedStrings
    , PackageImports
    , PatternSynonyms
    , QuantifiedConstraints
    , RankNTypes
    , RecursiveDo
    , ScopedTypeVariables
    , StandaloneDeriving
    , TemplateHaskell
    , TemplateHaskellQuotes
    , TupleSections
    , TypeApplications
    , TypeFamilies
    , TypeOperators
    , UndecidableInstances
    , ViewPatterns

library
  import: common
  hs-source-dirs: src

  build-depends:
      attoparsec
    , base
    , bytestring
    , snap-core
    , directory
    , filepath
    , text
    , unordered-containers

  exposed-modules:
      Obelisk.Snap.Extras

  ghc-options: -Wall -Werror -Wredundant-constraints -Wincomplete-uni-patterns -Wincomplete-record-updates -O

  if arch(javascript) || arch(wasm32)
    buildable: False
