cabal-version: 3.4
name:          obelisk-setup
version:       0.1
license:       BSD-3-Clause
data-dir:      data
data-files:    shim.js

library
  default-language: Haskell2010
  hs-source-dirs:   src
  exposed-modules:
    Obelisk.Setup.Utils
  ghc-options: -Wall
  build-depends:
    base >= 4.7 && < 5,
    Cabal >= 3.0 && < 4,
    directory >= 1.3.6 && < 2,
    filepath >= 1.4 && < 2

  if !(arch(javascript) || arch(wasm32))
    exposed-modules:
      Obelisk.Setup.Backend
      Obelisk.Setup.Frontend.Js
      Obelisk.Setup.Frontend.Wasm
      Obelisk.Setup.Static
    other-modules:
      Paths_obelisk_setup
    autogen-modules:
      Paths_obelisk_setup
    build-depends:
      containers,
      obelisk-asset-manifest,
      process >= 1.6 && < 2,
      text
