cabal-version: 2.2
name: obelisk-executable-config-lookup
version: 0.1.1
build-type: Simple

common common
  default-language: Haskell2010

  default-extensions:
      ApplicativeDo
    , BangPatterns
    , CPP
    , ConstraintKinds
    , DataKinds
    , DefaultSignatures
    , DeriveFunctor
    , DeriveGeneric
    , EmptyCase
    , EmptyDataDecls
    , FlexibleContexts
    , FlexibleInstances
    , FunctionalDependencies
    , GADTs
    , GeneralizedNewtypeDeriving
    , ImportQualifiedPost
    , KindSignatures
    , LambdaCase
    , LiberalTypeSynonyms
    , MultiParamTypeClasses
    , NumDecimals
    , OverloadedStrings
    , PackageImports
    , PatternSynonyms
    , QuantifiedConstraints
    , RankNTypes
    , RecursiveDo
    , ScopedTypeVariables
    , StandaloneDeriving
    , TemplateHaskell
    , TemplateHaskellQuotes
    , TupleSections
    , TypeApplications
    , TypeFamilies
    , TypeOperators
    , UndecidableInstances
    , ViewPatterns

library
  import: common
  exposed-modules: Obelisk.ExecutableConfig.Lookup, Obelisk.Configs

  if impl(ghcjs) || arch(javascript) || arch(wasm32)
    hs-source-dirs: src-js, src
    build-depends: ghcjs-dom
  else
    hs-source-dirs: src-other, src
    other-modules: Obelisk.Configs.Internal.Directory
    build-depends: directory

  build-depends:
    base,
    base64-bytestring,
    bytestring,
    containers,
    exceptions,
    exception-transformers,
    filepath,
    jsaddle,
    mmorph,
    monad-control,
    mtl,
    primitive,
    ref-tf,
    reflex-dom-core,
    reflex,
    text,
    transformers-base,
    transformers

  ghc-options: -Wall
