name: github-action

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0', '9.2', '9.4', '9.6', '9.8', '9.10', '9.12']
        os: ['ubuntu-latest', 'macos-13'] # https://github.com/haskell-actions/setup/issues/77
    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}

    - name: Install system packages (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install libsodium-dev

    - name: Install system packages (macos)
      if: matrix.os == 'macos-13'
      run: |
        brew update
        brew install libsodium

    - name: Install dependencies
      run: |
        cabal update
        cd lib && cabal build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Build obelisk libraries
      run: cd lib && cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cd lib && cabal test all
